config/routes.rb
Rails.application.routes.draw do
  

  root 'groups#index'

    resources :users
    resources :groups
    resources :user_group_roles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_group_roles,:dependent => :destroy
    accepts_nested_attributes_for :user_group_roles, :reject_if => lambda { |a| a[:user_id].blank? }, :allow_destroy => true
	has_many :users, through: :user_group_roles
	validates_presence_of :name
	validate :one_person_should_be_director


	def one_person_should_be_director
		count = 0
		user_group_roles.each do |usr|
			p 'hi'
			p usr
			if usr.role_id.present?
				if usr.role_id == PITConstant::Role::DIRECTOR
					count += 1
				end
			end
		end
		if count > 1
			errors.add(:base, "should be only once")
			errors.add('user_group_roles.role_id', "Each group should contain only one DIRECTOR")
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_group_roles
	has_many :groups, through: :user_group_roles
end

app/models/user_group_role.rb
class UserGroupRole < ApplicationRecord
	belongs_to :group
	belongs_to :user
	Roles = {
		"Director" => PITConstant::Role::DIRECTOR,
		"Assistant Director" => PITConstant::Role::ASSISTANT_DIRECTOR,
		"Member" => PITConstant::Role::MEMBER
	}

	validates_presence_of :user_id, :role_id
	validates :user_id, uniqueness: { scope: :role_id }
	# validates_uniqueness_of :user_id, scope: [:role_id,:group_id], :message => "user and role combination should be only once"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def edit
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
    user_group_role = @group.user_group_roles.build
  end

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    p group_params
    if @group.save
      redirect_to @group
    else
      p @group.errors
      render action: 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      redirect_to @group
    else
      render action: 'edit'
    end
  end
  private
    def group_params
      params.require(:group).permit(:name,:details,user_group_roles_attributes: [:id, :user_id,:role_id,:group_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# remove link doesn't work!!!!!!!!!
  	def link_to_remove_fields(name, f)
    	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  	end

  	# This now sort of works but the field disappears when it is created after about a second.  It also appears at the top of the page.  
  	def link_to_add_fields(name, f, association)  
    	new_object = f.object.class.reflect_on_association(association).klass.new  
    	fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|  
      		render(association.to_s.singularize + "_fields", :f => builder)  
    	end  
    	link_to name, "#", :onclick => h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), remote: true 
  	end 
 #  	def link_to_add_fields(name, f, association)
 #  		new_object = f.object.class.reflect_on_association(association).klass.new
 #  		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
 #    		render(association.to_s.singularize + "_fields", :f => builder)
 #  		end
 #  		link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
	# end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/user_group_roles_helper.rb
module UserGroupRolesHelper
	def role_text(string)
		case string
		when PITConstant::Role::DIRECTOR
			return "Director"
		when PITConstant::Role::ASSISTANT_DIRECTOR
			return "Assistant Director"
		when PITConstant::Role::MEMBER
			return "Member"
		else
			return ""
		end
	end
end

app/views/groups/_form.html.erb
<div class="row">
	<%= form_for @group do |f| %> 
		<div class="col-md-12">
			<% if @group.errors.any? %>
			  <div id="error_explanation">
			    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
			 
			    <ul>
			    <% @group.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			<% end %>
		    <div class="row">
			  <div class="form-group">
			    <label for="name" class="col-sm-2 control-label" required = "true"> Name</label>
			    <div class="col-sm-4">
			    	<%= f.text_field :name, :class => "form-control", :placeholder => "Enter Group Name" %>
			    </div>
			  </div>
			</div></br>
			<div class="row">
			  <div class="form-group">
			    <label for="name" class="col-sm-2 control-label">Details (optional)</label>
			    <div class="col-sm-4">
			    	<%= f.text_area :details, :class => "form-control", :placeholder => "Enter Details",:rows => 3,:cols => 4 %>
			    </div>
			  </div>
			</div></br>
			<div class="row">
				<h4>Adding Group Members</h4>
				<%= f.fields_for :user_group_roles do |builder| %>
					<%= render "user_group_role_fields", :f => builder %>
				<% end %>
				<div class="add_links">
			      <%= link_to_add_fields 'Add New Members', f, :user_group_roles%>
				</div>
			</div></br>

			<%= f.submit "Save Group", class: "btn btn-md btn-primary",:id => "form_submit" %>
			<%=link_to "Cancel", groups_path, :class => "btn btn-md btn-default" %>
		</div>
	<% end %>
</div>

app/views/groups/_user_group_role_fields.html.erb
<div class="col-md-12">
	<div class="row">
		<div class ="col-md-6">
	  		<div class="form-group">
	    		<label for="user_id" class="control-label">User Name</label>
	    		<%= f.collection_select :user_id, User.all, :id, :name,{:prompt => "Select User"},:class => "user_field" %>
	  		</div>
		</div>
		<div class ="col-md-6">
	  		<div class="form-group">
	    		<label for="user_id" class="control-label">Role</label></br>
    			<%= f.select :role_id, options_for_select(UserGroupRole::Roles,f.object.role_id),{:prompt => "Select Role"},:class => "role_field" %>
	  		</div>
		</div>
	</div>
</div>

app/views/groups/edit.html.erb
<h3>Edit Group <%= @group.name %></h3>
<%= render 'form' %>

app/views/groups/index.html.erb
<h3>Groups</h3>
<div class="row">
	<div class="col-md-10">
		<% if @groups.present? %>
			<table class="table table-striped" id="users_table">
				<thead>
					<tr>
						<th>Name</th>
						<th>Detail</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<% @groups.each do |group| %>
						<tr>
							<td><%= link_to(group.name , group) %></td>
							<td><%= group.details %></td>
							<td><%=link_to 'Edit', edit_group_path(group) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% else %>
			No Records Found
		<% end %>
	</div>
</div>

app/views/groups/new.html.erb
<h3>Add New Group</h3>
<%= render 'form' %>

app/views/groups/show.html.erb
<h3>Group</h3>
<%=link_to 'Edit', edit_group_path(@group) %> | <%=link_to 'New', new_group_path %> | <%=link_to 'View All Groupsps', groups_path %></br></br>
<div class="row">
	<div class="col-md-12">	
		<div class="row">
			<div class="col-md-3">
				<b>Name </b>
			</div>
			<div class="col-md-7"><%= @group.name %></div>
		</div></br>
		<div class="row">
			<div class="col-md-3">
				<b>Details </b>
			</div>
			<div class="col-md-7"><%= @group.details %></div>
		</div>
	</div>
</div>

<h3>List Of Users </h3>

<div class="row">
	<div class="col-md-10">
		<% if @group.user_group_roles.present? %>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Name </th>
						<th>Email</th>
						<th>Gender</th>
						<th>Role</th>
					</tr>
				</thead>
				<tbody>
					<% @group.user_group_roles.each do |usr| %>
						<tr>
							<td><%= link_to(usr.user.name , usr.user) %></td>
							<td><%= usr.user.email %></td>
							<td><%= usr.user.gender %></td>
							<td><%= role_text(usr.role_id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% else %>
			No Records Found
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PITSoultionsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  	<body>
		<div class="container-fluid text-center">    
		  <div class="row content">
		    <div class="col-sm-8 text-left"> 
		      <h1>PIT Solutions Machine Test</h1>
		      <%= yield %>
		    </div>
		  </div>
		</div>
	</body>
</html>